# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Richard Johnson
email: falsecard@me.com
website: www.datarich.org

# Social links
twitter_username: truecard
github_username:  falsecard

facebook_username: falsecard

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Richard 

  I am 

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in learning and statistics some of my other activities are:
   - Ashtanga, Run, Cycle
   - Language: French, Polish, Sanskrit 
   - Crossword


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
